---
title: "Failure model comparison"
author: Steve Whitlock
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Taglife_failure_model_comparison}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}

library(failCompare)

```

### loading data

load the example data set from Rocky Reach Dam, Washigton State.

```{r load}
data(sockeye)
taglife=sockeye$days   # vector of tag failure times

# taglife=c(6.12,10.42,12.33,13.62,13.62,14.29,14.46,14.67,14.79,14.96,15.04,15.12,15.21,15.33,15.42,15.50,15.50,15.62,15.67,
# 15.75,15.75,15.79,15.87,16.04,16.08,16.08,16.08,16.17,16.17,16.17,16.25,16.25,16.29,16.29,16.37,16.37,16.54,16.71,
# 16.71,16.71,16.71,16.79,16.83,17.42,17.58,17.71,17.71,17.96,18.04,18.50)


taglife

```

### Creating a failure model object

```{r single_mod,warning=FALSE}

weib_mod=fc_fit(time=taglife,model="weibull")
weib_mod

vit13_mod=fc_fit(time=taglife,model="vitality.4p")
vit13_mod

```
### Plotting separate model objects

```{r fig, fig.width=11, fig.height=5,echo=TRUE,warning=FALSE,fig.width=5, fig.height=5}

  par(mfrow=c(1,2))
  plot(weib_mod)
  plot(vit13_mod)
```

### Creating alternate model sets

```{r mod sets,warning=FALSE,fig.width=5, fig.height=5,echo=F}

gomp=fc_fit(taglife,model="gompertz")

fmods=fc_fit(taglife,model=c("gengamma","gompertz","gamma","lognormal"))
fmods


fmods=fc_fit(taglife,model=c("gengamma","gompertz"))
fmods=fc_fit(taglife,model=c("gengamma","gompertz","gamma","lognormal"))

par(mfrow=c(1,1))
plot(fmods)


# just gengamma
gg=fc_fit(taglife,model=c("gengamma"))
plot(gg)

fc_pred(times = 1:20,model = "gengamma", pars = fmods$par_tab[fmods$par_tab$model=="gengamma",3])
fc_pred(times = 1:20,model = "gengamma", pars = fmods$par_tab[7:9,3])

fmods_r=fc_rank(fmods)
plot(fmods_r)

# fc_rank(fmods)
```

### Ranking models
```{r mod rank,warning=FALSE,fig.width=5, fig.height=5,echo=T}

taglife=sockeye[,1]

aa=fc_fit(taglife,"weibull")
fc_fit(taglife,"weibull3")
# fc_fit(taglife,"weibull3",SEs = F)

# fc_fit(taglife,model=c("vitality.4p"))

# fc_fit(taglife,model=c("gompertz","weibull3"))


# fc_fit(rnorm(14,10,3),"weibull3",SEs = F)


# fc_tryfit()
# 
# 
# fc_fit(taglife,"weibull3",SEs=F)
# fc_fit(taglife,"weibull3",SEs=T)
# 
# fc_fit(taglife,"vitality.ku",SEs=F)
# 
# # # THESE THROW ERRORS
# dnn=fc_fit(taglife,"vitality.4p",SEs=T)
# dnnn=fc_fit(taglife,"vitality.4p",SEs=F)
# dn=fc_fit(taglife,"all",SEs=T)
# dn$par_tab
# 
# 
# data(chinook)
# taglife=chinook[,"days"]
# 
# taglife=c(rep(1,3),rep(50,3))
# 
# y=taglife
# y_sfrac=fc_surv(taglife)
# vitality::vitality.4p(time = sort(y),sdata = y_sfrac,pplot =F,silent = T,se=T)
# vitality::vitality.4p(time = sort(y),sdata = y_sfrac,pplot =F,silent = T,se=F)
# 
# the_call=quote(vitality::vitality.4p(time = sort(y),sdata = y_sfrac,pplot =F,silent = T,se=T))
# the_call=quote(vitality::vitality.4p(time = sort(y),sdata = y_sfrac,pplot =F,silent = T,se=F))
# 
# fc_tryfit(fit_call = the_call,y = taglife,model="vitality.4p")
# 

```

